name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get dependencies
        run: sudo apt-get install cmake zip unzip build-essential checkinstall zlib1g-dev libssl-dev -y

      - name: Compile zsign
        run: mkdir build; cd build && cmake .. && make

      - name: Rename the binary
        run: mv build/zsign zsign-linux-x86-64
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: zsign-linux-x86-64
